Holdings display notification #159
Center-for-Research-Libraries/vufind pull request #162
Opened 2022-09-30 19:30 UTC by KimSarabia

## Description
Adds notification to warn users of current data issues where listings are out of order.
<img width="717" alt="Screen Shot 2022-09-30 at 2 28 55 PM" src="https://user-images.githubusercontent.com/11491604/193343087-4c2823e4-b59c-41a1-bfdb-93369fccaf67.png">

closes #159

2022-10-03 16:12 UTC, ryan-jacobs requested changes
Thanks @KimSarabia! I added some notes in-line. Regrading some examples, I think #149 offers some cases and other context.

2022-10-03 16:12 UTC, ryan-jacobs commented on themes/crl/templates/RecordTab/holdingsils.phtml
> +      <?php if (count($holding['items']) > 5):?>
Since this is a threshold check that could theoretically change, and is repeated, I suggest either:

- Setting a boolean template variable earlier on like `$isLongItemList = count($holding['items']) > 5 ? true : false;` and then just checking `$isLongItemList` every time needed.
- Setting a threshold variable earlier, like `$longItemList = 5;` and the making a condition against `$longItemList` every time needed.

This way we have a central place to modify the variable if needed (everything is more DRY and easier to maintain).

The 2nd option is probably best here since I see that `$holding` is not set until fairly far into the template logic.

2022-10-03 16:12 UTC, ryan-jacobs commented on themes/crl/less/crl_global.less
> +}
An alert style is a nice idea. However, since we are already using bootstrap we should have some alert classes available already - https://getbootstrap.com/docs/3.3/components/#alerts

The `alert alert-info` might be the best fit as anything red seems to signal an error, which isn't technically what we have here with this ordering situation. This is more of a "heads up" and "we're always improving our system" kind of message.

2022-10-03 16:12 UTC, ryan-jacobs commented on themes/crl/templates/RecordTab/holdingsils.phtml
> +      <th><?=$this->transEsc("Description")?><?php if (count($holding['items']) > 5):?><i class="fa fa-warning"></i><?php endif; ?></th>
Keeping in line with the idea that we don't want to characterize this message as an "error", perhaps an "info" glyph, in a more subtle color, would be most appropriate here. Something like `glyphicon-info-sign` or a nice font awesome equivalent.

2022-10-03 16:12 UTC, ryan-jacobs commented on themes/crl/templates/RecordTab/holdingsils.phtml
> +          <?=$this->transEsc('Notice: This list is currently out of chronological order. We appreciate your patience as we work towards improving our holdings data.') ?>
I promised to provide some placeholder text here. I like this structure, and suggest the following adjustment:

> Notice: Some item lists may not be in chronological order. We appreciate your patience as CRL refines its holdings metadata to address this and improve discovery and borrowing experiences.

The problem is not universal as some long lists do sort correctly, notably those that have numeric volume identifiers in the description already. The analytics team is currently looking at ways to make numeric descriptors universal. We don't really have a way to "detect" which lists are **both** long and out-of-order, so for now we can just detect the long lists and make our message generic to both correct and incorrect ordering cases.

2022-10-04 16:46 UTC, KimSarabia commented
@ryan-jacobs Here's a screenshot
<img width="934" alt="Screen Shot 2022-10-04 at 11 42 53 AM" src="https://user-images.githubusercontent.com/11491604/193878484-71e876d5-756d-40ef-b420-a246165b465b.png">

2022-10-04 18:59 UTC, ryan-jacobs reviewed
This all looks good to me. I should have an opportunity to share the newest screenshot with Amy and Marie Thurs morning during another call that we have. If they agree, lets merge Thurs.

2022-10-06 15:51 UTC, ryan-jacobs commented
@KimSarabia, Everyone found the visual treatment appropriate for this need, but the message needs small adjustment to become:

> Notice: Some item lists may not be in chronological order. We appreciate your patience as CRL addresses this issue.

2022-10-06 20:05 UTC, merged